package proyectobancoed;

import javax.swing.JOptionPane;

/**
 *
 * @author Melissa Ruiz Cruz
 */
public class Menu extends javax.swing.JFrame {
    ///////////////RECURSIVIDAD //////////////////
    private static int idCounter = 0;
    private static int Id() {
        return ++idCounter;
    }
    Fila f = new Fila();
    BD b = new BD();
    Reporte r = new Reporte();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BotonInsertarUsuario = new javax.swing.JMenuItem();
        BotonDesEncolar = new javax.swing.JMenuItem();
        BotonCalculadora = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        BotonMostrarFila = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        BotonBusacrBD = new javax.swing.JMenuItem();
        BotonMostrarBD = new javax.swing.JMenuItem();
        BtonEditarBD = new javax.swing.JMenuItem();
        BotonEliminarBD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        BotonMostrarReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/KAwu.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyecto Banco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(51, 0, 204))); // NOI18N

        jMenu1.setText("Usuario");

        BotonInsertarUsuario.setText("Ingresar Usuario");
        BotonInsertarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(BotonInsertarUsuario);

        BotonDesEncolar.setText("Atender primero en fila");
        BotonDesEncolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDesEncolarActionPerformed(evt);
            }
        });
        jMenu1.add(BotonDesEncolar);

        BotonCalculadora.setText("Calculadora de Impuestos");
        BotonCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculadoraActionPerformed(evt);
            }
        });
        jMenu1.add(BotonCalculadora);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Fila de Banco");

        BotonMostrarFila.setText("Mostrar Fila de Banco");
        BotonMostrarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarFilaActionPerformed(evt);
            }
        });
        jMenu4.add(BotonMostrarFila);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Base de Datos");

        BotonBusacrBD.setText("Buscar en Base de Datos");
        BotonBusacrBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBusacrBDActionPerformed(evt);
            }
        });
        jMenu2.add(BotonBusacrBD);

        BotonMostrarBD.setText("Mostrar Base de Datos");
        BotonMostrarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarBDActionPerformed(evt);
            }
        });
        jMenu2.add(BotonMostrarBD);

        BtonEditarBD.setText("Editar Usuario en Base de Datos");
        BtonEditarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonEditarBDActionPerformed(evt);
            }
        });
        jMenu2.add(BtonEditarBD);

        BotonEliminarBD.setText("Eliminar Usaurio en Base de Datos");
        BotonEliminarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarBDActionPerformed(evt);
            }
        });
        jMenu2.add(BotonEliminarBD);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reporte");

        BotonMostrarReporte.setText("Mostrar Reporte");
        BotonMostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarReporteActionPerformed(evt);
            }
        });
        jMenu3.add(BotonMostrarReporte);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInsertarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarUsuarioActionPerformed
        // TODO add your handling code here:
        String NombreN = JOptionPane.showInputDialog(null, "Digite el nombre:");
        int CedulaN = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite la cédula: "));
        String NumTelN = JOptionPane.showInputDialog(null, "Digite el número de teléfono: ");
        int EdadN = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite la edad: "));
        String DireccionN = JOptionPane.showInputDialog(null, "Digite la dirección: ");
        //int idN = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el id: "));
        int idN = Id();
        String EstadoN = "Normal";
        
        f.insertarFila(NombreN, CedulaN, NumTelN, EdadN, DireccionN, idN,EstadoN);
        b.insertarBD(NombreN, CedulaN, NumTelN, EdadN, DireccionN, idN, EstadoN);
        r.insertarReporte(NombreN, CedulaN, NumTelN, EdadN, DireccionN, idN, EstadoN);
        JOptionPane.showMessageDialog(null, "Se Inserto el Usuario Exitosamente...");
    }//GEN-LAST:event_BotonInsertarUsuarioActionPerformed

    private void BotonEliminarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarBDActionPerformed
        // TODO add your handling code here:
        b.Eliminar(r);
    }//GEN-LAST:event_BotonEliminarBDActionPerformed

    private void BtonEditarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonEditarBDActionPerformed
        // TODO add your handling code here:
        b.editarBD(r);
    }//GEN-LAST:event_BtonEditarBDActionPerformed

    private void BotonMostrarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarBDActionPerformed
        // TODO add your handling code here:
        b.mostrarBD();
    }//GEN-LAST:event_BotonMostrarBDActionPerformed

    private void BotonMostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarReporteActionPerformed
        // TODO add your handling code here:
        r.mostrarReporte();
    }//GEN-LAST:event_BotonMostrarReporteActionPerformed

    private void BotonBusacrBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBusacrBDActionPerformed
        // TODO add your handling code here:
        b.Buscar();
    }//GEN-LAST:event_BotonBusacrBDActionPerformed

    private void BotonMostrarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarFilaActionPerformed
        // TODO add your handling code here:
        f.mostrarFila();
    }//GEN-LAST:event_BotonMostrarFilaActionPerformed

    private void BotonDesEncolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDesEncolarActionPerformed
        f.desencolarFila();
    }//GEN-LAST:event_BotonDesEncolarActionPerformed

    private void BotonCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculadoraActionPerformed
        f.calculadora();
        
    }//GEN-LAST:event_BotonCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BotonBusacrBD;
    private javax.swing.JMenuItem BotonCalculadora;
    private javax.swing.JMenuItem BotonDesEncolar;
    private javax.swing.JMenuItem BotonEliminarBD;
    private javax.swing.JMenuItem BotonInsertarUsuario;
    private javax.swing.JMenuItem BotonMostrarBD;
    private javax.swing.JMenuItem BotonMostrarFila;
    private javax.swing.JMenuItem BotonMostrarReporte;
    private javax.swing.JMenuItem BtonEditarBD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
